// common/src/main/ets/constants/RouteConstants.ets

export class RouteConstants {
  static readonly INDEX: string                = 'pages/Index'
  static readonly GUIDE_SWIPER: string         = 'pages/GuideSwiperPage'
  static readonly EDITOR: string               = 'pages/EditorPage'
  static readonly THEME: string                = 'pages/ThemePage'
  static readonly MATERIAL_TAB: string         = 'pages/MaterialTabPage'
  static readonly RELATIONSHIP_TAB: string     = 'pages/RelationshipTabPage'
  static readonly MY_TAB: string              = 'pages/MyTabPage'
  static readonly CHARACTER_DETAIL: string     = 'pages/CharacterDetailPage'
  static readonly WORLD_SETTING_DETAIL: string = 'pages/WorldSettingDetailPage'
  static readonly INSPIRATION_CREATE: string   = 'pages/InspirationCreatePage'
  static readonly INSPIRATION_LIST: string     = 'pages/InspirationListPage'
}
